---
title: "Plots and models"
output: html_document
---

1. Wd + files
```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(exactRankTests)
library(lme4)
library(langcog)
library(brms)

##library(psychometric)
##library(multilevel)
##library(nlme)

##library(Rmisc)
##library(lattice)
##library(plyr)

## library(devtools)
## devtools::install_github("langcog/langcog")

data <- read.csv2("data_file_stimulus.csv")
data
```


2. Plots hol versus seq Mittelwerte
```{r cars}
plot_1 <- ggplot(data = data, aes(x = condition, col = object_str)) +
  labs (x = "condition", y = "object_str") +
  geom_bar() 

plot_2 <- ggplot(data = data, aes(x = condition, col = feature_str)) +
  labs (x = "condition", y = "feature_str") +
  geom_bar() 

plot_3 <- ggplot(data = data, aes(x = condition, col = object_se)) +
  labs (x = "condition", y = "object_se") +
  geom_bar() 

plot_4 <- ggplot(data = data, aes(x = condition, col = feature_se)) +
  labs (x = "condition", y = "feature_se") +
  geom_bar() 

plot_1
plot_2
plot_3
plot_4

```


3. Percent correct, seperate for each stimulus

```{r pressure, echo=FALSE}

### dependent variable: rel versus (irr + ne)
data_rel_not <- data %>%
  separate(stimulus_nc, c("object", "predicate"), remove = F) %>%
  mutate(object_str = ifelse(object_str == "rel", "1", "0"),
         object_str = as.numeric(as.character(object_str))) %>%
  mutate(feature_str = ifelse(feature_str == "rel", "1", "0")) %>%
  mutate(feature_str = as.numeric(as.character(feature_str))) %>%
  mutate(object_se = ifelse(object_se == "rel", "1", "0")) %>%
  mutate(object_se = as.numeric(as.character(object_se))) %>%
  mutate(feature_se = ifelse(feature_se == "rel", "1", "0")) %>%
  mutate(feature_se = as.numeric(as.character(feature_se)))
``` 


```{r pressure, echo=FALSE}
## percent correct for feature_str separate for each object stimulus 
d1os <- data_rel_not %>%
  mutate(condition = ifelse(condition == "hol","holistic","sequential")) %>%
  group_by(condition, object, id) %>%
  summarise(object_str = mean(object_str))

# ?? CI
d2os <- data_rel_not %>%
  mutate(condition = ifelse(condition == "hol","holistic","sequential")) %>%
  group_by(condition, object) %>%
  summarise(object_str = mean(object_str))

plot_5 <- ggplot() +
  geom_jitter(data = d1os, aes(x = object, y = object_str, col = condition), position = position_jitterdodge(jitter.width = .2, jitter.height = 0.05,dodge.width = 0.5), alpha = .3)+
  geom_pointrange(data = d2os,aes(x = object, y = object_str, col = condition, ymin = 0, ymax = 1), 
                  position = position_dodge(width = .5), size = 0.6, pch = 5) +
  guides(alpha = F)+
  labs(x="Picture")+
  scale_y_continuous(name = "Proportion Correct", limits = c(-0.05,1.05))+
  theme_few() + 
  scale_colour_solarized()

plot_5


## percent correct for feature_str separate for each object stimulus
d1fs <- data_rel_not %>%
  mutate(condition = ifelse(condition == "hol","holistic","sequential")) %>%
  group_by(condition, predicate, id) %>%
  summarise(feature_str = mean(feature_str))

d2fs <- data_rel_not %>%
  mutate(condition = ifelse(condition == "hol","holistic","sequential")) %>%
  group_by(condition, predicate) %>%
  summarise(feature_str = mean(feature_str))

plot_6 <- ggplot() +
  geom_jitter(data = d1fs, aes(x = predicate, y = feature_str, col = condition), position = position_jitterdodge(jitter.width = .2, jitter.height = 0.05,dodge.width = 0.5), alpha = .3)+
  geom_pointrange(data = d2fs,aes(x = predicate, y = feature_str, col = condition, ymin = 0, ymax = 1), 
                  position = position_dodge(width = .5), size = 0.6, pch = 5) +
  guides(alpha = F)+
  labs(x="Picture")+
  scale_y_continuous(name = "Proportion Correct", limits = c(-0.05,1.05))+
  theme_few() + 
  scale_colour_solarized()

plot_6


## percent correct for object_se separate for each object stimulus
d1os <- data_rel_not %>%
  mutate(condition = ifelse(condition == "hol","holistic","sequential")) %>%
  group_by(condition, object, id) %>%
  summarise(object_se = mean(object_se))

d2os <- data_rel_not %>%
  mutate(condition = ifelse(condition == "hol","holistic","sequential")) %>%
  group_by(condition, object) %>%
  summarise(object_se = mean(object_se))

plot_7 <- ggplot() +
  geom_jitter(data = d1os, aes(x = object, y = object_se, col = condition), position = position_jitterdodge(jitter.width = .2, jitter.height = 0.05,dodge.width = 0.5), alpha = .3)+
  geom_pointrange(data = d2os,aes(x = object, y = object_se, col = condition, ymin = 0, ymax = 1), 
                  position = position_dodge(width = .5), size = 0.6, pch = 5) +
  guides(alpha = F)+
  labs(x="Picture")+
  scale_y_continuous(name = "Proportion Correct", limits = c(-0.05,1.05))+
  theme_few() + 
  scale_colour_solarized()

plot_7


### percent correct for feature_se separate for each object stimulus
d1fs <- data_rel_not %>%
  mutate(condition = ifelse(condition == "hol","holistic","sequential")) %>%
  group_by(condition, predicate, id) %>%
  summarise(feature_se = mean(feature_se))

d2fs <- data_rel_not %>%
  mutate(condition = ifelse(condition == "hol","holistic","sequential")) %>%
  group_by(condition, predicate) %>%
  summarise(feature_se = mean(feature_se))

plot_8 <- ggplot() +
  geom_jitter(data = d1fs, aes(x = predicate, y = feature_se, col = condition), position = position_jitterdodge(jitter.width = .2, jitter.height = 0.05,dodge.width = 0.5), alpha = .3)+
  geom_pointrange(data = d2fs,aes(x = predicate, y = feature_se, col = condition, ymin = 0, ymax = 1), 
                  position = position_dodge(width = .5), size = 0.6, pch = 5) +
  guides(alpha = F)+
  labs(x="Picture")+
  scale_y_continuous(name = "Proportion Correct", limits = c(-0.05,1.05))+
  theme_few() + 
  scale_colour_solarized()

plot_8

#######
#### d2os <- data_obj_str %>%
#  mutate(condition = ifelse(condition == "hol","holistic","sequential")) %>%
#  group_by(condition, object) %>%
#  summarise(object_str = mean(object_str), ci=0.95)

## installation of langcog failed
# d2os <- d1os %>%
#   multi_boot_standard(col = "object_str")

# d3os <- d1os %>%
#  group_by(condition, id)%>%
#  summarise(object_str = mean(object_str)) %>%
# multi_boot_standard(col = "object_str")%>%
#  mutate(stimulus = "Overall")

## d4.p4 <- d4.p2 %>%
#  group_by(Age, block, dyad_id)%>%
#  summarise(comp = mean(comp)) %>%
#  multi_boot_standard(col = "comp")%>%
#  mutate(stimulus = "Overall")


plot1 <- data_rel_not%>%
  select(-X, - repetitions, -X.1)%>%
  gather(dimension, correct,-condition, -id, -stimulus_nc,-object, -predicate, -responses)

plot2 <- plot1%>%
  group_by(condition, dimension)%>%
  multi_boot_standard(col = "correct")


ggplot() +
  geom_jitter(data = plot1, aes(x = dimension, y = correct, col = condition), position = position_jitterdodge(jitter.width = .2, jitter.height = 0.05,dodge.width = 0.5), alpha = .3)+
  geom_pointrange(data = plot2,aes(x = dimension, y = mean, col = condition, ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .5), size = 0.6, pch = 5) +
  guides(alpha = F)+
  labs(x="Picture")+
  scale_y_continuous(name = "Proportion Correct", limits = c(-0.05,1.05))+
  theme_few() + 
  scale_colour_solarized()
```


4. two.sided t.test (rel versus not) 

```{r}
## feature_str
t.test(feature_str ~ condition,
       alternative = c("two.sided"), data_rel_not)

## object_str
t.test(object_str ~ condition,
       alternative = c("two.sided"), data_rel_not)
```






4. Calculate baysian models

feature content: 

```{r}


## data file models

# use number of words instead
data_length <- data %>%
  add_column(data$stimulus_nc) %>%
  separate(stimulus_nc, c("object", "predicate")) %>%
  mutate(responses = ifelse(responses == "", NA, as.character(responses)))%>%
  mutate(characters = nchar(responses)) %>%
  mutate(characters = as.numeric(as.character(characters)))

data_of_structure <- data %>%
  separate(stimulus_nc, c("object", "predicate"), remove = F) %>%
  mutate(object_str = ifelse(object_str == "ne", "0", "1")) %>%
  mutate(object_str = as.numeric(as.character(object_str))) %>%
  mutate(feature_str = ifelse(feature_str == "ne", "0", "1")) %>%
  mutate(feature_str = as.numeric(as.character(feature_str))) %>%
  mutate(obj_fea = ifelse(object_str == 1 & feature_str == 1, "1", "0")) %>%
   mutate(property = ifelse(predicate == "jump" | predicate == "run", "movement",
                           ifelse(predicate == "big" | predicate == "small", "size","number")))%>%
  mutate(class = ifelse(object == "ball" | object == "bike" | object == "comb" | object == "bike" | object == "fork" | object == "hammer", "object","animal"))%>%
  mutate(obj_fea = as.numeric(as.character(obj_fea)))
  
  
data_fea_content <- data %>%
  add_column(data$stimulus_nc) %>%
  separate(stimulus_nc, c("object", "predicate")) %>%
  mutate(feature_str = ifelse(feature_str == "rel", "1", "0")) %>%
  mutate(feature_str = as.numeric(as.character(feature_str)))

# Bayesian model object-feature structure

m1_of <- brm(obj_fea ~ condition * property + (condition * property | id) + (condition | stimulus_nc),
                    data = data_of_structure, family = bernoulli(),
          control = list(adapt_delta = 0.99, max_treedepth = 20),
          sample_prior = F,
          cores = 4,
          chains = 4,
          inits = 0,
          iter = 5000)%>%
  add_criterion("waic")%>%
  saveRDS(.,"../saves/m1_of.rds")

m1_of <- readRDS("../saves/m1_of.rds")

# ... additional models

# model comparison 
loo_compare(m1_of, m2_of, m3_of, criterion = "waic")%>%
  as.data.frame() %>%
  tibble::rownames_to_column("Predictors")%>%
  mutate(
    Predictors = recode(Predictors, 
                   m1_of = "condition * Condition", 
                   m2_of = "Age + Condition",
                   m3_of = "Age"),
    weight = exp(elpd_waic) / sum(exp(elpd_waic)),
    weight = round(weight, 2),
    WAIC = round(waic, 2),
    SE = round(se_waic,2))%>%
  select(Predictors, WAIC, SE, weight)



### length  ## hier keine binäre Codierung, Modell funktioniert nicht
m1_l <- glmer(characters ~ condition + (condition * predicate | id) + (1 | stimulus_nc), family = binomial, data = data_length,control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

m2_l <- glmer(characters ~ condition + predicate + (condition * predicate | id) + (1 | data$stimulus_nc), family = binomial, data = data_length,control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

m3_l <- glmer(characters ~ predicate + (condition * predicate | id) + (1 | data$stimulus_nc), family = binomial, data = data_length,control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))


### object-feature structure
m1_of <- glmer(obj_fea ~ condition * predicate + (condition * predicate | id) + (1 | data$stimulus_nc), family = binomial, data = data_of_structure,control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

m2_of <- glmer(obj_fea ~ condition + predicate + (condition * predicate | id) + (1 | data$stimulus_nc), family = binomial, data = data_of_structure,control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

m3_of <- glmer(obj_fea ~ predicate + (condition * predicate | id) + (1 | data$stimulus_nc), family = binomial, data = data_of_structure,control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))


### feature content
m1_fc <- glmer(feature_str ~ condition * predicate + (condition * predicate | id) + (1 | data$stimulus_nc), family = binomial, data = data_fea_content,control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

p_m1_fc <- drop1(m1_fc, test = "Chisq")

m2_fc <- glmer(feature_str ~ condition + predicate + (condition * predicate | id) + (1 | data$stimulus_nc), family = binomial, data = data_fea_content,control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

m3_fc <- glmer(feature_str ~ predicate + (condition * predicate | id) + (1 | data$stimulus_nc), family = binomial, data = data_fea_content,control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

```


5. Word Clouds -  seperate word cloud for each object and predicate

```{r}
## create data file for wordclouds

data_file <- read.csv2("data_file.csv")%>%
  select(-X)

data_words <- read.csv2("Words_data_codiert.csv")%>%
  select(-X)

data_wordcloud <- data_file %>%
  left_join(data_words)

############
data_wordcloud <- data_file %>%
  mutate(pmatch(value, object, nomatch = NA_integer_, duplicates.ok = FALSE))

data_wordcloud <- data_file %>%
  mutate(type = ifelse(is.element(value, object) == TRUE, "object"))

data_wordcloud <- data_file %>%
  mutate(type = ifelse(value %in% "object", "object"))

data_wordcloud <- data_file %>%
  mutate_each(type = ifelse(value %in% "object", "object"))

data_wordcloud <- data_file %>%
  mutate(type = ifelse("value" %in% object, "object"))

is.element(x, y)



data_wordcloud <- data_file %>%
  mutate(pmatch(value, object, nomatch = NA_integer_, duplicates.ok = FALSE))


pmatch(x, table, nomatch = NA_integer_, duplicates.ok = FALSE)


if (x < 5) 1 else 2



##########
######  a <- match(data_file$type, object, nomatch = NA_integer_, incomparables = NULL)


jump <- data_file %>%
  filter(predicate == "jump") %>%
  group_by(value) %>%
  summarise(freq = n()) %>%
  arrange(-freq)

jump

jump <- data_file_pretest %>%
  filter(predicate == "jump") %>%
  pull(value) %>%
  unique()

jump


oap <- c("ball", "bike", "cat", "comb", "duck", "elephant", "fork", "hammer", "monkey", "many", "one", "small", "big", "jump", "run")

docs <- c("Hund", "Katze", "Maus", "Hund", "Hase", "Kind", "Hase", "Hase", "Hase", "Hase", "Hase")


## generate wordclouds
wordcloud(c(docs), seq(1, 1000, len = 62),
          colors=brewer.pal(8, "Dark2"))

wordcloud(c(docs), seq(1, 1000, len = 62),
          colors=brewer.pal(8, "Dark2"))

```





