---
title: "Video selection rec_mean"
output: html_document
---

```{r load_packages, include = FALSE}
library(tidyverse)

```


```{r}
gram_data <- read_csv(file="../data/pt2_data_video_select.csv")%>%
  select(-X1)
```

```{r}
gram_data%>%
  group_by(condition)%>%
  summarise(n = length(unique(id)))
```

"diff" codes whether child mada any attempt to differentiate between two versions of the stimuli. 

```{r}
# selecting relevant videos
to_select <- gram_data %>%
  filter(diff == "yes", predicate != "static")%>%
  mutate(hol_or_atom = ifelse(hol_or_atom == "0", "holistisch", "sequentiell"))%>%
  group_by(sex, age, condition,stimulus,hol_or_atom)%>%
  summarise(n = length(unique(id)))%>%
  group_by(sex, age,condition,stimulus)%>%
  mutate(count = length(hol_or_atom))%>%
  filter(count > 1)%>%
  group_by(stimulus,hol_or_atom)%>%
  summarise(n = n())


write_excel_csv2(to_select, "../video_select.csv")

```


```{r}
sample(rep(c("6f","6m","8f","8m"),40))
```

  [1] "8f" "8f" "6m" "6m" "6m" "8f" "6f" "6m" "6m" "8m" "6f" "8m" "6f" "6m" "8f" "8m" "8m" "8m" "6m" "6f" "8f" "8m" "8f" "8m" "6m" "8m" "6f" "8m" "6f" "8f"
 [31] "6f" "8m" "8f" "6f" "8m" "8m" "8f" "6m" "8f" "6f" "8f" "8m" "6f" "6m" "8m" "8f" "8f" "6m" "6m" "8m" "6m" "6m" "8m" "6f" "6m" "8f" "8f" "6m" "6m" "8m"
 [61] "8m" "6f" "8m" "6m" "8f" "6m" "8m" "8m" "6f" "8f" "8f" "8m" "8m" "8m" "6m" "8m" "6m" "6f" "6f" "6f" "8f" "6m" "6f" "6f" "6m" "6f" "6f" "6f" "6f" "8m"
 [91] "6f" "8f" "6f" "8f" "8m" "6m" "8m" "8f" "8m" "6f" "6m" "6m" "6f" "8f" "6m" "8m" "6m" "6m" "8f" "8m" "6f" "6f" "6m" "6f" "8m" "6m" "6f" "8f" "6m" "8f"
[121] "8m" "8f" "8f" "8f" "6f" "6m" "6m" "8f" "6f" "8f" "8m" "6m" "6f" "8f" "8f" "6f" "8f" "8m" "8f" "6f" "8f" "6f" "8m" "8m" "8f" "8m" "6m" "8m" "6f" "8f"
[151] "8f" "6m" "8m" "6m" "6f" "6m" "6m" "6f" "8f" "6f"


```{r}
gram_data %>%
  filter(diff == "yes", predicate != "static")%>%
  mutate(hol_or_atom = ifelse(hol_or_atom == "0", "holistisch", "sequentiell"))%>%
  filter(stimulus %in% to_select$stimulus)%>%
  filter(
    stimulus == "bike_many"
    #,hol_or_atom == "holistisch"
    ,hol_or_atom == "sequentiell"
    ,sex == "f"
    #,sex == "m"
    ,age == "8"
    #,age == "8"
  )%>%
  mutate(id = id)
```



